def prepare_potato(robots):
    GoToObject(robots[0], 'Potato')
    PickupObject(robots[0], 'Potato')
    GoToObject(robots[0], 'Knife')
    PickupObject(robots[0], 'Knife')
    GoToObject(robots[0], 'Potato')
    SliceObject(robots[0], 'Potato')
    GoToObject(robots[0], 'CounterTop')
    PutObject(robots[0], 'Knife', 'CounterTop')
    GoToObject(robots[0], 'Potato')
    PickupObject(robots[0], 'Potato')

def setup_stove(robots):
    GoToObject(robots[1], 'Pan')
    PickupObject(robots[1], 'Pan')
    GoToObject(robots[1], 'StoveBurner')
    PutObject(robots[1], 'Pan', 'StoveBurner')
    GoToObject(robots[1], 'StoveKnob')
    SwitchOn(robots[1], 'StoveKnob')

def cook_potato(robots):
    GoToObject(robots[0], 'Pan')
    PutObject(robots[0], 'Potato', 'Pan')
    time.sleep(10)
    GoToObject(robots[0], 'StoveKnob')
    SwitchOff(robots[0], 'StoveKnob')

def store_potato(robots):
    GoToObject(robots[0], 'Pan')
    PickupObject(robots[0], 'Potato')
    GoToObject(robots[0], 'Fridge')
    OpenObject(robots[0], 'Fridge')
    PutObject(robots[0], 'Potato', 'Fridge')
    CloseObject(robots[0], 'Fridge')

task1_thread = threading.Thread(target=prepare_potato, args=(robots,))
task2_thread = threading.Thread(target=setup_stove, args=(robots,))
task1_thread.start()
task2_thread.start()
task1_thread.join()
task2_thread.join()
task3_thread = threading.Thread(target=cook_potato, args=(robots,))
task3_thread.start()
task3_thread.join()
task4_thread = threading.Thread(target=store_potato, args=(robots,))
task4_thread.start()
task4_thread.join()
action_queue.append({'action':'Done'})
action_queue.append({'action':'Done'})
action_queue.append({'action':'Done'})
action_queue.append({'action':'Done'})
task_over = True
time.sleep(5)