def execute_task():
    GoToObject(robots[0], 'Pen')
    GoToObject(robots[3], 'Book')
    GoToObject(robots[1], 'Laptop')
    PickupObject(robots[0], 'Pen')
    PickupObject(robots[3], 'Book')
    PickupObject(robots[1], 'Laptop')
    GoToObject(robots[0], 'Drawer')
    GoToObject(robots[3], 'Shelf')
    GoToObject(robots[1], 'SideTable')
    OpenObject(robots[0], 'Drawer')
    PutObject(robots[3], 'Book', 'Shelf')
    PutObject(robots[1], 'Laptop', 'SideTable')
    PutObject(robots[0], 'Pen', 'Drawer')
    GoToObject(robots[3], 'Newspaper')
    GoToObject(robots[1], 'Vase')
    CloseObject(robots[0], 'Drawer')
    PickupObject(robots[3], 'Newspaper')
    PickupObject(robots[1], 'Vase')
    GoToObject(robots[0], 'CreditCard')
    GoToObject(robots[3], 'GarbageCan')
    GoToObject(robots[1], 'Shelf')
    PickupObject(robots[0], 'CreditCard')
    OpenObject(robots[3], 'GarbageCan')
    PutObject(robots[1], 'Vase', 'Shelf')
    GoToObject(robots[0], 'Drawer')
    PutObject(robots[3], 'Newspaper', 'GarbageCan')
    GoToObject(robots[1], 'Statue')
    OpenObject(robots[0], 'Drawer')
    CloseObject(robots[3], 'GarbageCan')
    PickupObject(robots[1], 'Statue')
    PutObject(robots[0], 'CreditCard', 'Drawer')
    GoToObject(robots[3], 'Pillow')
    GoToObject(robots[1], 'SideTable')
    CloseObject(robots[0], 'Drawer')
    PickupObject(robots[3], 'Pillow')
    PutObject(robots[1], 'Statue', 'SideTable')
    GoToObject(robots[0], 'KeyChain')
    GoToObject(robots[3], 'Sofa')
    PickupObject(robots[0], 'KeyChain')
    PutObject(robots[3], 'Pillow', 'Sofa')
    GoToObject(robots[0], 'Drawer')
    OpenObject(robots[0], 'Drawer')
    PutObject(robots[0], 'KeyChain', 'Drawer')
    CloseObject(robots[0], 'Drawer')
    GoToObject(robots[0], 'Watch')
    PickupObject(robots[0], 'Watch')
    GoToObject(robots[0], 'Drawer')
    OpenObject(robots[0], 'Drawer')
    PutObject(robots[0], 'Watch', 'Drawer')
    CloseObject(robots[0], 'Drawer')
    GoToObject(robots[0], 'RemoteControl')
    PickupObject(robots[0], 'RemoteControl')
    GoToObject(robots[0], 'Drawer')
    OpenObject(robots[0], 'Drawer')
    PutObject(robots[0], 'RemoteControl', 'Drawer')
    CloseObject(robots[0], 'Drawer')