def execute_task(robots):
    GoToObject(robots[0], 'Knife')
    GoToObject(robots[1], 'Plate')
    PickupObject(robots[0], 'Knife')
    PickupObject(robots[1], 'Plate')
    GoToObject(robots[0], 'Lettuce')
    GoToObject(robots[1], 'Sink')
    PickupObject(robots[0], 'Lettuce')
    CleanObject(robots[1], 'Plate')
    SliceObject(robots[0], 'Lettuce')
    GoToObject(robots[1], 'CounterTop')
    GoToObject(robots[0], 'CounterTop')
    PutObject(robots[1], 'Plate', 'CounterTop')
    PutObject(robots[0], 'Lettuce', 'CounterTop')
    GoToObject(robots[0], 'Tomato')
    PickupObject(robots[0], 'Tomato')
    SliceObject(robots[0], 'Tomato')
    GoToObject(robots[0], 'CounterTop')
    PutObject(robots[0], 'Tomato', 'CounterTop')
    GoToObject(robots[0], 'Bread')
    PickupObject(robots[0], 'Bread')
    SliceObject(robots[0], 'Bread')
    GoToObject(robots[0], 'CounterTop')
    PutObject(robots[0], 'Bread', 'CounterTop')
    GoToObject(robots[0], 'Apple')
    GoToObject(robots[1], 'CounterTop')
    PickupObject(robots[0], 'Apple')
    PickupObject(robots[1], 'Bread')
    SliceObject(robots[0], 'Apple')
    GoToObject(robots[1], 'Plate')
    GoToObject(robots[0], 'Bowl')
    PutObject(robots[1], 'Bread', 'Plate')
    GoToObject(robots[1], 'CounterTop')
    PutObject(robots[0], 'Apple', 'Bowl')
    GoToObject(robots[0], 'CounterTop')
    PickupObject(robots[1], 'Lettuce')
    GoToObject(robots[1], 'Plate')
    PutObject(robots[0], 'Knife', 'CounterTop')
    PutObject(robots[1], 'Lettuce', 'Plate')
    GoToObject(robots[1], 'CounterTop')
    PickupObject(robots[1], 'Tomato')
    GoToObject(robots[1], 'Plate')
    PutObject(robots[1], 'Tomato', 'Plate')
    GoToObject(robots[1], 'Bowl')
    PickupObject(robots[1], 'Bowl')
    GoToObject(robots[1], 'Plate')
    PutObject(robots[1], 'Bowl', 'Plate')