def process_supplies(robots):
    GoToObject(robots[0], 'Knife')
    GoToObject(robots[1], 'Pot')
    PickupObject(robots[0], 'Knife')
    CleanObject(robots[1], 'Pot')
    GoToObject(robots[0], 'Apple')
    SliceObject(robots[0], 'Apple')
    GoToObject(robots[0], 'Bread')
    SliceObject(robots[0], 'Bread')
    GoToObject(robots[0], 'Lettuce')
    SliceObject(robots[0], 'Lettuce')
    GoToObject(robots[0], 'Tomato')
    SliceObject(robots[0], 'Tomato')
    PickupObject(robots[0], 'Tomato')
    GoToObject(robots[1], 'Apple')
    GoToObject(robots[0], 'Pot')
    PickupObject(robots[1], 'Apple')
    PutObject(robots[0], 'Tomato', 'Pot')
    GoToObject(robots[1], 'Pot')
    GoToObject(robots[0], 'Bread')
    PutObject(robots[1], 'Apple', 'Pot')
    PickupObject(robots[0], 'Bread')
    GoToObject(robots[1], 'Lettuce')
    GoToObject(robots[0], 'Pot')
    PickupObject(robots[1], 'Lettuce')
    PutObject(robots[0], 'Bread', 'Pot')
    GoToObject(robots[1], 'Pot')
    PutObject(robots[1], 'Lettuce', 'Pot')
    GoToObject(robots[0], 'Fridge')
    PickupObject(robots[1], 'Pot')
    OpenObject(robots[0], 'Fridge')
    GoToObject(robots[1], 'Fridge')
    PutObject(robots[1], 'Pot', 'Fridge')
    CloseObject(robots[1], 'Fridge')

def execute_task():
    task_thread = threading.Thread(target=process_supplies, args=(robots,))
    task_thread.start()
    task_thread.join()
    action_queue.append({'action':'Done'})
    task_over = True
    time.sleep(5)