def secure_kitchen(robots):
    GoToObject(robots[0], 'CoffeeMachine')
    GoToObject(robots[1], 'Blinds')
    GoToObject(robots[2], 'Fridge')
    SwitchOff(robots[0], 'CoffeeMachine')
    CloseObject(robots[1], 'Blinds')
    CloseObject(robots[2], 'Fridge')
    GoToObject(robots[0], 'LightSwitch')
    GoToObject(robots[1], 'Cabinet')
    SwitchOff(robots[0], 'LightSwitch')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[0], 'Microwave')
    GoToObject(robots[1], 'Cabinet')
    SwitchOff(robots[0], 'Microwave')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[0], 'StoveKnob')
    GoToObject(robots[1], 'Cabinet')
    SwitchOff(robots[0], 'StoveKnob')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[0], 'StoveKnob')
    GoToObject(robots[1], 'Cabinet')
    SwitchOff(robots[0], 'StoveKnob')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[0], 'StoveKnob')
    GoToObject(robots[1], 'Cabinet')
    SwitchOff(robots[0], 'StoveKnob')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[0], 'StoveKnob')
    GoToObject(robots[1], 'Cabinet')
    SwitchOff(robots[0], 'StoveKnob')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[0], 'Toaster')
    GoToObject(robots[1], 'Cabinet')
    SwitchOff(robots[0], 'Toaster')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[1], 'Cabinet')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[1], 'Cabinet')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[1], 'Cabinet')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[1], 'Cabinet')
    CloseObject(robots[1], 'Cabinet')
    GoToObject(robots[1], 'Drawer')
    CloseObject(robots[1], 'Drawer')
    GoToObject(robots[1], 'Drawer')
    CloseObject(robots[1], 'Drawer')
    GoToObject(robots[1], 'Drawer')
    CloseObject(robots[1], 'Drawer')
    GoToObject(robots[1], 'Window')
    CloseObject(robots[1], 'Window')

task1_thread = threading.Thread(target=secure_kitchen, args=(robots,))
task1_thread.start()
task1_thread.join()
action_queue.append({'action':'Done'})
task_over = True
time.sleep(5)