def execute_task(robots):
    GoToObject(robots[0], 'FloorLamp')
    GoToObject(robots[1], 'SideTable')
    SwitchOn(robots[0], 'FloorLamp')
    CleanObject(robots[1], 'SideTable')
    GoToObject(robots[0], 'LightSwitch')
    PickupObject(robots[1], 'Pen')
    PutObject(robots[1], 'Pen', 'SideTable')
    SwitchOn(robots[0], 'LightSwitch')
    GoToObject(robots[1], 'Dresser')
    GoToObject(robots[0], 'Sofa')
    CleanObject(robots[1], 'Dresser')
    CleanObject(robots[0], 'Sofa')
    PickupObject(robots[1], 'KeyChain')
    PutObject(robots[1], 'KeyChain', 'Dresser')
    GoToObject(robots[0], 'CoffeeTable')
    PickupObject(robots[1], 'Watch')
    PutObject(robots[1], 'Watch', 'Dresser')
    CleanObject(robots[0], 'CoffeeTable')
    GoToObject(robots[1], 'Drawer')
    PickupObject(robots[0], 'RemoteControl')
    PutObject(robots[0], 'RemoteControl', 'CoffeeTable')
    CleanObject(robots[1], 'Drawer')
    PickupObject(robots[0], 'Newspaper')
    PutObject(robots[0], 'Newspaper', 'CoffeeTable')
    GoToObject(robots[1], 'Drawer')
    GoToObject(robots[0], 'Shelf')
    CleanObject(robots[1], 'Drawer')
    CleanObject(robots[0], 'Shelf')
    GoToObject(robots[1], 'Drawer')
    PickupObject(robots[0], 'Book')
    PutObject(robots[0], 'Book', 'Shelf')
    CleanObject(robots[1], 'Drawer')
    GoToObject(robots[0], 'Drawer')
    CleanObject(robots[0], 'Drawer')