def toast_bread(robots):
    GoToObject(robots[0], 'Knife')
    PickupObject(robots[0], 'Knife')
    GoToObject(robots[0], 'Bread')
    SliceObject(robots[0], 'Bread')
    GoToObject(robots[0], 'Toaster')
    SwitchOn(robots[0], 'Toaster')
    GoToObject(robots[0], 'Bread')
    PickupObject(robots[0], 'Bread')
    GoToObject(robots[0], 'Toaster')
    PutObject(robots[0], 'Bread', 'Toaster')
    time.sleep(5)
    GoToObject(robots[0], 'Toaster')
    SwitchOff(robots[0], 'Toaster')
    GoToObject(robots[0], 'Bread')
    PickupObject(robots[0], 'Bread')
    GoToObject(robots[0], 'Plate')
    PutObject(robots[0], 'Bread', 'Plate')

task_thread = threading.Thread(target=toast_bread, args=(robots,))
task_thread.start()
task_thread.join()
action_queue.append({'action':'Done'})
task_over = True
time.sleep(5)