def toast_bread(robots):
    GoToObject(robots[0], 'Knife')
    PickupObject(robots[0], 'Knife')
    GoToObject(robots[0], 'Bread')
    SliceObject(robots[0], 'Bread')
    GoToObject(robots[0], 'CounterTop')
    PutObject(robots[0], 'Knife', 'CounterTop')
    GoToObject(robots[0], 'Bread')
    PickupObject(robots[0], 'Bread')
    GoToObject(robots[0], 'Toaster')
    OpenObject(robots[0], 'Toaster')
    PutObject(robots[0], 'Bread', 'Toaster')
    CloseObject(robots[0], 'Toaster')
    SwitchOn(robots[0], 'Toaster')
    time.sleep(5)
    SwitchOff(robots[0], 'Toaster')
    OpenObject(robots[0], 'Toaster')
    PickupObject(robots[0], 'Bread')
    CloseObject(robots[0], 'Toaster')
    GoToObject(robots[0], 'Plate')
    PutObject(robots[0], 'Bread', 'Plate')

task1_thread = threading.Thread(target=toast_bread, args=(robots,))
task1_thread.start()
task1_thread.join()
action_queue.append({'action':'Done'})
task_over = True
time.sleep(5)