def slice_and_store(robots):
    def robot1_task(robot):
        GoToObject(robot, 'Knife')
        PickupObject(robot, 'Knife')
        GoToObject(robot, 'Lettuce')
        PickupObject(robot, 'Lettuce')
        SliceObject(robot, 'Lettuce')
        GoToObject(robot, 'Fridge')
        OpenObject(robot, 'Fridge')
        GoToObject(robot, 'Lettuce')
        PickupObject(robot, 'Lettuce')
        GoToObject(robot, 'Fridge')
        PutObject(robot, 'Lettuce', 'Fridge')
        CloseObject(robot, 'Fridge')

    def robot2_task(robot):
        GoToObject(robot, 'Knife')
        PickupObject(robot, 'Knife')
        GoToObject(robot, 'Tomato')
        PickupObject(robot, 'Tomato')
        SliceObject(robot, 'Tomato')
        GoToObject(robot, 'Fridge')
        OpenObject(robot, 'Fridge')
        GoToObject(robot, 'Tomato')
        PickupObject(robot, 'Tomato')
        GoToObject(robot, 'Fridge')
        PutObject(robot, 'Tomato', 'Fridge')
        CloseObject(robot, 'Fridge')

    task1_thread = threading.Thread(target=robot1_task, args=(robots[0],))
    task2_thread = threading.Thread(target=robot2_task, args=(robots[1],))
    task1_thread.start()
    task2_thread.start()
    task1_thread.join()
    task2_thread.join()
    action_queue.append({'action':'Done'})
    action_queue.append({'action':'Done'})
    task_over = True
    time.sleep(5)