def wash_knife_and_slice_lettuce(robots):
    GoToObject(robots[0], 'Knife')
    PickupObject(robots[0], 'Knife')
    GoToObject(robots[0], 'Sink')
    SwitchOn(robots[0], 'Faucet')
    CleanObject(robots[0], 'Knife')
    time.sleep(2)
    SwitchOff(robots[0], 'Faucet')
    GoToObject(robots[0], 'Lettuce')
    SliceObject(robots[0], 'Lettuce')
    PickupObject(robots[0], 'LettuceSliced')
    GoToObject(robots[0], 'CounterTop')
    PutObject(robots[0], 'Knife', 'CounterTop')

task1_thread = threading.Thread(target=wash_knife_and_slice_lettuce, args=(robots,))
task1_thread.start()
task1_thread.join()
action_queue.append({'action':'Done'})
task_over = True
time.sleep(5)