def cook_potato(robots):
    GoToObject(robots[0], 'Potato')
    GoToObject(robots[1], 'Pan')
    PickupObject(robots[0], 'Potato')
    GoToObject(robots[0], 'Knife')
    PickupObject(robots[0], 'Knife')
    SliceObject(robots[0], 'Potato')
    GoToObject(robots[1], 'StoveBurner')
    PutObject(robots[1], 'Pan', 'StoveBurner')
    GoToObject(robots[1], 'StoveKnob')
    GoToObject(robots[0], 'Potato')
    SwitchOn(robots[1], 'StoveKnob')
    PickupObject(robots[0], 'Potato')
    GoToObject(robots[0], 'Pan')
    PutObject(robots[0], 'Potato', 'Pan')
    GoToObject(robots[0], 'StoveKnob')
    SwitchOff(robots[0], 'StoveKnob')
    GoToObject(robots[0], 'Pan')
    PickupObject(robots[0], 'Potato')
    GoToObject(robots[0], 'Fridge')
    OpenObject(robots[0], 'Fridge')
    PutObject(robots[0], 'Potato', 'Fridge')
    CloseObject(robots[0], 'Fridge')

task1_thread = threading.Thread(target=cook_potato, args=(robots,))
task1_thread.start()
task1_thread.join()
action_queue.append({'action':'Done'})
task_over = True
time.sleep(5)