def execute_task(robots):
    GoToObject(robots[0], 'Knife')
    GoToObject(robots[1], 'Plate')
    PickupObject(robots[0], 'Knife')
    PickupObject(robots[1], 'Plate')
    GoToObject(robots[0], 'Potato')
    GoToObject(robots[1], 'Sink')
    SliceObject(robots[0], 'Potato')
    CleanObject(robots[1], 'Plate')
    GoToObject(robots[0], 'Potato')
    PickupObject(robots[0], 'Potato')
    GoToObject(robots[0], 'Plate')
    PutObject(robots[0], 'Potato', 'Plate')