def put_plate_of_sliced_lettuce_in_microwave(robots):
    GoToObject(robots[0], 'Knife')
    PickupObject(robots[0], 'Knife')
    GoToObject(robots[0], 'Lettuce')
    SliceObject(robots[0], 'Lettuce')
    GoToObject(robots[0], 'CounterTop')
    PutObject(robots[0], 'Knife', 'CounterTop')
    GoToObject(robots[0], 'Lettuce')
    PickupObject(robots[0], 'Lettuce')
    GoToObject(robots[0], 'Plate')
    PutObject(robots[0], 'Lettuce', 'Plate')
    GoToObject(robots[0], 'Plate')
    PickupObject(robots[0], 'Plate')
    GoToObject(robots[0], 'Microwave')
    OpenObject(robots[0], 'Microwave')
    PutObject(robots[0], 'Plate', 'Microwave')
    CloseObject(robots[0], 'Microwave')

task1_thread = threading.Thread(target=put_plate_of_sliced_lettuce_in_microwave, args=(robots,))
task1_thread.start()
task1_thread.join()
action_queue.append({'action':'Done'})
task_over = True
time.sleep(5)